export const QUOTES = [
  "STAY HUNGRY, STAY FOOLISH.",
  "THE BEST WAY TO PREDICT THE FUTURE IS TO CREATE IT.",
  "DO NOT WAIT; THE TIME WILL NEVER BE 'JUST RIGHT'.",
  "DREAM BIG AND DARE TO FAIL.",
  "ACTION IS THE KEY TO ALL SUCCESS.",
  "EVERYTHING YOU'VE EVER WANTED IS ON THE OTHER SIDE OF FEAR.",
  "HARDSHIPS OFTEN PREPARE ORDINARY PEOPLE FOR AN EXTRAORDINARY DESTINY.",
  "BELIEVE YOU CAN AND YOU'RE HALFWAY THERE.",
  "YOUR LIMITATION—IT'S ONLY YOUR IMAGINATION.",
  "PUSH YOURSELF, BECAUSE NO ONE ELSE IS GOING TO DO IT FOR YOU.",
  "SOMETIMES LATER BECOMES NEVER. DO IT NOW.",
  "GREAT THINGS NEVER COME FROM COMFORT ZONES.",
  "DREAM IT. WISH IT. DO IT.",
  "SUCCESS DOESN'T JUST FIND YOU. YOU HAVE TO GO OUT AND GET IT.",
  "THE HARDER YOU WORK FOR SOMETHING, THE GREATER YOU'LL FEEL WHEN YOU ACHIEVE IT.",
  "DREAM BIGGER. DO BIGGER.",
  "DON'T STOP WHEN YOU'RE TIRED. STOP WHEN YOU'RE DONE.",
  "WAKE UP WITH DETERMINATION. GO TO BED WITH SATISFACTION.",
  "DO SOMETHING TODAY THAT YOUR FUTURE SELF WILL THANK YOU FOR.",
  "LITTLE THINGS MAKE BIG DAYS.",
  "IT ALWAYS SEEMS IMPOSSIBLE UNTIL IT'S DONE.",
  "KEEP YOUR EYES ON THE STARS, AND YOUR FEET ON THE GROUND.",
  "THE ONLY WAY TO DO GREAT WORK IS TO LOVE WHAT YOU DO.",
  "YOU MISS 100% OF THE SHOTS YOU DON'T TAKE.",
  "WHETHER YOU THINK YOU CAN OR YOU THINK YOU CAN'T, YOU'RE RIGHT.",
  "PERFECTION IS NOT ATTAINABLE, BUT IF WE CHASE PERFECTION WE CAN CATCH EXCELLENCE.",
  "I HAVE NOT FAILED. I'VE JUST FOUND 10,000 WAYS THAT WON'T WORK.",
  "LIMIT YOUR 'ALWAYS' AND YOUR 'NEVERS'.",
  "THE BEST REVENGE IS MASSIVE SUCCESS.",
  "THE ONLY LIMIT TO OUR REALIZATION OF TOMORROW WILL BE OUR DOUBTS OF TODAY."
];

export const CURATED_QUOTES: Record<string, { text: string; author: string }[]> = {
  "les-brown": [
    { text: "SHOOT FOR THE MOON. EVEN IF YOU MISS, YOU'LL LAND AMONG THE STARS.", author: "Les Brown" },
    { text: "YOU ARE NEVER TOO OLD TO SET ANOTHER GOAL OR TO DREAM A NEW DREAM.", author: "Les Brown" },
    { text: "HELP OTHERS ACHIEVE THEIR DREAMS AND YOU WILL ACHIEVE YOURS.", author: "Les Brown" },
    { text: "IT'S NOT OVER UNTIL YOU WIN.", author: "Les Brown" },
    { text: "YOU MUST BE WILLING TO DO THE THINGS TODAY OTHERS WON'T DO IN ORDER TO HAVE THE THINGS TOMORROW OTHERS WON'T HAVE.", author: "Les Brown" }
  ],
  "steve-jobs": [
    { text: "STAY HUNGRY, STAY FOOLISH.", author: "Steve Jobs" },
    { text: "THE ONLY WAY TO DO GREAT WORK IS TO LOVE WHAT YOU DO.", author: "Steve Jobs" },
    { text: "INNOVATION DISTINGUISHES BETWEEN A LEADER AND A FOLLOWER.", author: "Steve Jobs" },
    { text: "YOUR TIME IS LIMITED, SO DON'T WASTE IT LIVING SOMEONE ELSE'S LIFE.", author: "Steve Jobs" },
    { text: "HAVE THE COURAGE TO FOLLOW YOUR HEART AND INTUITION.", author: "Steve Jobs" }
  ],
  "maya-angelou": [
    { text: "I'VE LEARNED THAT PEOPLE WILL FORGET WHAT YOU SAID, BUT PEOPLE WILL NEVER FORGET HOW YOU MADE THEM FEEL.", author: "Maya Angelou" },
    { text: "NOTHING WILL WORK UNLESS YOU DO.", author: "Maya Angelou" },
    { text: "YOU MAY ENCOUNTER MANY DEFEATS, BUT YOU MUST NOT BE DEFEATED.", author: "Maya Angelou" },
    { text: "IF YOU DON'T LIKE SOMETHING, CHANGE IT. IF YOU CAN'T CHANGE IT, CHANGE YOUR ATTITUDE.", author: "Maya Angelou" },
    { text: "MY MISSION IN LIFE IS NOT MERELY TO SURVIVE, BUT TO THRIVE.", author: "Maya Angelou" }
  ],
  "oprah-winfrey": [
    { text: "THE BIGGEST ADVENTURE YOU CAN TAKE IS TO LIVE THE LIFE OF YOUR DREAMS.", author: "Oprah Winfrey" },
    { text: "TURN YOUR WOUNDS INTO WISDOM.", author: "Oprah Winfrey" },
    { text: "YOU BECOME WHAT YOU BELIEVE.", author: "Oprah Winfrey" },
    { text: "LUCK IS A MATTER OF PREPARATION MEETING OPPORTUNITY.", author: "Oprah Winfrey" },
    { text: "CHALLENGES ARE GIFTS THAT FORCE US TO SEARCH FOR A NEW CENTER OF GRAVITY.", author: "Oprah Winfrey" }
  ],
  "zig-ziglar": [
    { text: "YOU DON'T HAVE TO BE GREAT TO START, BUT YOU HAVE TO START TO BE GREAT.", author: "Zig Ziglar" },
    { text: "YOUR ATTITUDE, NOT YOUR APTITUDE, WILL DETERMINE YOUR ALTITUDE.", author: "Zig Ziglar" },
    { text: "IF YOU CAN DREAM IT, YOU CAN ACHIEVE IT.", author: "Zig Ziglar" },
    { text: "PEOPLE OFTEN SAY THAT MOTIVATION DOESN'T LAST. WELL, NEITHER DOES BATHING - THAT'S WHY WE RECOMMEND IT DAILY.", author: "Zig Ziglar" },
    { text: "EXPECT THE BEST. PREPARE FOR THE WORST. CAPITALIZE ON WHAT COMES.", author: "Zig Ziglar" }
  ]
};

export const WEATHER = [
  "LONDON: 12°C CLOUDY",
  "NEW YORK: 18°C SUNNY",
  "TOKYO: 22°C CLEAR",
  "PARIS: 15°C RAIN",
  "BERLIN: 10°C WINDY",
  "SYDNEY: 25°C SUNNY",
  "DUBAI: 35°C HOT",
  "MOSCOW: -5°C SNOW",
  "ROME: 20°C SUNNY",
  "SAN FRANCISCO: 16°C FOG",
  "LOS ANGELES: 24°C CLEAR",
  "CHICAGO: 8°C CHILLY",
  "MIAMI: 28°C HUMID",
  "SEATTLE: 14°C DRIZZLE",
  "AUSTIN: 26°C BRIGHT"
];

export const HEADLINES = [
  "TECH GIANT ANNOUNCES NEW AI MODEL",
  "SPACE MISSION REACHES MARS ORBIT",
  "GLOBAL MARKETS SHOW STEADY GROWTH",
  "SCIENTISTS DISCOVER NEW DEEP SEA SPECIES",
  "RENEWABLE ENERGY SURPASSES FOSSIL FUELS",
  "LOCAL TEAM WINS CHAMPIONSHIP",
  "NEW BREAKTHROUGH IN MEDICAL RESEARCH",
  "ART EXHIBITION OPENS IN PARIS",
  "HISTORIC PEACE TREATY SIGNED",
  "ELECTRIC VEHICLE SALES HIT RECORD HIGH",
  "NEW ARCHAEOLOGICAL FIND IN EGYPT",
  "OCEAN CLEANUP PROJECT SHOWS SUCCESS",
  "GLOBAL SUMMIT ON CLIMATE ACTION BEGINS",
  "INNOVATIVE STARTUP SECURES MAJOR FUNDING",
  "WORLD'S OLDEST TREE DISCOVERED IN CHILE",
  "NEW DESIGN FOR SUSTAINABLE CITIES UNVEILED",
  "BREAKTHROUGH IN QUANTUM COMPUTING REPORTED",
  "MAJOR ART RESTORATION PROJECT COMPLETED",
  "NEW SPECIES OF BUTTERFLY FOUND IN AMAZON",
  "GLOBAL LITERACY RATES REACH NEW HIGH"
];

export const CUSTOM_MESSAGES = [
  "WELCOME TO RETROBOARD",
  "HAVE A PRODUCTIVE DAY",
  "TIME FOR A COFFEE BREAK?",
  "KEEP CALM AND CARRY ON",
  "YOU ARE DOING GREAT",
  "ENJOY THE LITTLE THINGS",
  "FOCUS ON THE POSITIVE",
  "MAKE TODAY AMAZING",
  "BE THE CHANGE YOU WISH TO SEE",
  "STAY FOCUSED, STAY HUMBLE",
  "BREATHE IN, BREATHE OUT",
  "THE BEST IS YET TO COME",
  "CHASE YOUR DREAMS",
  "STAY CURIOUS",
  "KINDNESS IS FREE"
];
